import Head from 'next/head'

export default function Header () {
    return <Head>
    <title>Polls</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="author" content="Pello Altadill" />
    <link rel="icon" href="/favicon.ico" />
</Head>;
}

